# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-28 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jitter', '0002_auto_20210628_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
